[build]
  builder = "docker"
  publish = "backend/dist"

[build.environment]
  NODE_ENV = "production"

[[build.env]]
  name = "NODE_ENV"
  value = "production"

[deploy]
  startCommand = "node dist/main"
  numInstances = 1
  cpuType = "shared"
  memoryMiB = 512